"""Shared PR/comment footer helpers for consistent Kōan branding.

Provides a single ``build_koan_footer()`` function used across review
comments, quality reports, plan issues, and PR bodies — so the branded
link and provider/model attribution stay consistent everywhere.
"""

import logging
import re
import subprocess
import time
from typing import List

KOAN_URL = "https://koan.anantys.com"
_logger = logging.getLogger(__name__)
KOAN_BRANDED = f"[Kōan]({KOAN_URL})"


def format_duration(seconds: float) -> str:
    """Format seconds into a compact human-readable string.

    Examples: ``"45s"``, ``"5 min 34s"``, ``"1 h 12 min"``.
    """
    total = int(seconds)
    if total < 60:
        return f"{total}s"
    minutes, secs = divmod(total, 60)
    if minutes < 60:
        return f"{minutes} min {secs}s" if secs else f"{minutes} min"
    hours, mins = divmod(minutes, 60)
    return f"{hours} h {mins} min" if mins else f"{hours} h"

_LEGACY_FOOTER_PATTERNS: List[re.Pattern] = [
    re.compile(
        r"^\s*\*Generated by K(?:ō|o)an[^*]*\*\s*$", re.MULTILINE,
    ),
    re.compile(
        r"^\s*_Generated by\s*\[?K(?:ō|o)an\]?[^\n]*$", re.MULTILINE,
    ),
    re.compile(
        r"^\s*🤖\s*Generated with\s*\[?Claude Code\]?[^\n]*$", re.MULTILINE,
    ),
    re.compile(
        r"^\s*_Automated review by\s*\[?K(?:ō|o)an\]?[^\n]*$", re.MULTILINE,
    ),
]


def _provider_label(provider_name: str) -> str:
    """Return a human-readable provider label."""
    return provider_name[:1].upper() + provider_name[1:] if provider_name else ""


def build_koan_footer(
    action: str = "Generated by",
    provider_name: str = "",
    model: str = "",
    extra_parts: List[str] | None = None,
) -> str:
    """Build a branded footer line.

    Examples::

        build_koan_footer()
        # → '_Generated by [Kōan](https://koan.anantys.com)_'

        build_koan_footer(action="Automated review by", provider_name="claude", model="opus-4-6")
        # → '_Automated review by [Kōan](...)_ _(Claude · model opus-4-6)_'
    """
    base = f"_{action} {KOAN_BRANDED}_"
    parts = []
    if provider_name:
        parts.append(_provider_label(provider_name))
    if model:
        parts.append(f"model {model}")
    if extra_parts:
        parts.extend(part for part in extra_parts if part)
    if parts:
        return f"{base} _({' · '.join(parts)})_"
    return base


def build_mission_footer(
    provider_name: str = "",
    model: str = "",
    head_sha: str = "",
    duration_seconds: float | int | None = None,
) -> str:
    """Build the rich footer used by Python-created mission PRs."""
    extra_parts = []
    if head_sha:
        extra_parts.append(f"HEAD={head_sha[:7]}")
    if duration_seconds is not None:
        extra_parts.append(format_duration(float(duration_seconds)))
    return build_koan_footer(
        provider_name=provider_name,
        model=model,
        extra_parts=extra_parts,
    )


def resolve_footer_provider_model(
    project_name: str = "",
    model_key: str = "mission",
) -> tuple[str, str]:
    """Resolve the configured provider and model for a footer.

    This is best-effort: footer generation must not break PR creation if
    provider/config lookup fails.
    """
    provider_name = ""
    model = ""
    try:
        from app.provider import get_provider_name

        provider_name = get_provider_name()
    except Exception as exc:
        _logger.debug("Footer provider lookup failed: %s", exc)
        provider_name = ""

    try:
        from app.config import get_model_config

        models = get_model_config(project_name)
        if isinstance(models, dict):
            model = str(models.get(model_key, "") or "")
    except Exception as exc:
        _logger.debug("Footer model lookup failed: %s", exc)
        model = ""

    return provider_name, model


def _short_head(project_path: str = "") -> str:
    if not project_path:
        return ""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=project_path,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        _logger.debug("git rev-parse failed for %s: %s", project_path, exc)
        return ""
    if result.returncode != 0:
        _logger.debug(
            "git rev-parse exited %d for %s: %s",
            result.returncode,
            project_path,
            result.stderr.strip(),
        )
        return ""
    return result.stdout.strip()


def _elapsed_label(started_at: float | int | str | None = None) -> str:
    if started_at in (None, ""):
        return ""
    try:
        elapsed = max(0, int(time.time() - float(started_at)))
    except (TypeError, ValueError) as exc:
        _logger.debug("Footer elapsed parsing failed for %r: %s", started_at, exc)
        return ""
    if elapsed < 60:
        return f"{elapsed}s"
    minutes, seconds = divmod(elapsed, 60)
    if minutes < 60:
        return f"{minutes}m{seconds:02d}s"
    hours, minutes = divmod(minutes, 60)
    return f"{hours}h{minutes:02d}m"


def build_pr_footer(
    action: str = "Generated by",
    project_name: str = "",
    model_key: str = "mission",
    project_path: str = "",
    started_at: float | int | str | None = None,
    provider_name: str = "",
    model: str = "",
) -> str:
    """Build a PR footer with provider, model, HEAD, and duration metadata."""
    if not provider_name and not model:
        provider_name, model = resolve_footer_provider_model(project_name, model_key)

    extra_parts = []
    head = _short_head(project_path)
    if head:
        extra_parts.append(f"HEAD={head}")
    elapsed = _elapsed_label(started_at)
    if elapsed:
        extra_parts.append(elapsed)

    return build_koan_footer(
        action=action,
        provider_name=provider_name,
        model=model,
        extra_parts=extra_parts,
    )


def append_koan_footer(
    body: str,
    footer: str,
) -> str:
    """Return *body* with exactly one trailing Kōan footer."""
    body = strip_legacy_footers(body or "")
    if body:
        return f"{body}\n\n---\n{footer}"
    return footer


def strip_legacy_footers(body: str) -> str:
    """Remove known legacy/duplicate footer lines from a PR or comment body.

    Strips lines matching ``*Generated by Kōan …*``,
    ``🤖 Generated with Claude Code``, etc.  Also collapses any
    resulting trailing ``---`` separator that no longer precedes content.
    """
    for pat in _LEGACY_FOOTER_PATTERNS:
        body = pat.sub("", body)

    body = re.sub(r"\n{3,}", "\n\n", body)
    body = re.sub(r"\n+---\s*$", "", body)
    return body.rstrip()
