"""Shared PR/comment footer helpers for consistent Kōan branding.

Provides a single ``build_koan_footer()`` function used across review
comments, quality reports, plan issues, and PR bodies — so the branded
link and provider/model attribution stay consistent everywhere.
"""

import re
from typing import List

KOAN_URL = "https://koan.anantys.com"
KOAN_BRANDED = f"[Kōan]({KOAN_URL})"


def format_duration(seconds: float) -> str:
    """Format seconds into a compact human-readable string.

    Examples: ``"45s"``, ``"5 min 34s"``, ``"1 h 12 min"``.
    """
    total = int(seconds)
    if total < 60:
        return f"{total}s"
    minutes, secs = divmod(total, 60)
    if minutes < 60:
        return f"{minutes} min {secs}s" if secs else f"{minutes} min"
    hours, mins = divmod(minutes, 60)
    return f"{hours} h {mins} min" if mins else f"{hours} h"

_LEGACY_FOOTER_PATTERNS: List[re.Pattern] = [
    re.compile(
        r"^\s*\*Generated by K(?:ō|o)an[^*]*\*\s*$", re.MULTILINE,
    ),
    re.compile(
        r"^\s*_Generated by\s*\[?K(?:ō|o)an\]?[^\n]*$", re.MULTILINE,
    ),
    re.compile(
        r"^\s*🤖\s*Generated with\s*\[?Claude Code\]?[^\n]*$", re.MULTILINE,
    ),
    re.compile(
        r"^\s*_Automated review by\s*\[?K(?:ō|o)an\]?[^\n]*$", re.MULTILINE,
    ),
]


def build_koan_footer(
    action: str = "Generated by",
    provider_name: str = "",
    model: str = "",
) -> str:
    """Build a branded footer line.

    Examples::

        build_koan_footer()
        # → '_Generated by [Kōan](https://koan.anantys.com)_'

        build_koan_footer(action="Automated review by", provider_name="claude", model="opus-4-6")
        # → '_Automated review by [Kōan](...)_ _(Claude · model opus-4-6)_'
    """
    base = f"_{action} {KOAN_BRANDED}_"
    parts = []
    if provider_name:
        parts.append(provider_name.capitalize())
    if model:
        parts.append(f"model {model}")
    if parts:
        return f"{base} _({' · '.join(parts)})_"
    return base


def strip_legacy_footers(body: str) -> str:
    """Remove known legacy/duplicate footer lines from a PR or comment body.

    Strips lines matching ``*Generated by Kōan …*``,
    ``🤖 Generated with Claude Code``, etc.  Also collapses any
    resulting trailing ``---`` separator that no longer precedes content.
    """
    for pat in _LEGACY_FOOTER_PATTERNS:
        body = pat.sub("", body)

    body = re.sub(r"\n{3,}", "\n\n", body)
    body = re.sub(r"\n+---\s*$", "", body)
    return body.rstrip()
