"""Hosted-container (Railway) deployment helpers.

Active only when KOAN_DEPLOY=railway; every function is inert otherwise.
"""
import contextlib
import os
from pathlib import Path

TELEGRAM_KEYS = ("KOAN_TELEGRAM_TOKEN", "KOAN_TELEGRAM_CHAT_ID")
AUTH_KEYS = ("CLAUDE_CODE_OAUTH_TOKEN", "ANTHROPIC_API_KEY")
PROVISION_KEYS = (
    "CLAUDE_CODE_OAUTH_TOKEN", "ANTHROPIC_API_KEY", "GH_TOKEN",
    "KOAN_TELEGRAM_TOKEN", "KOAN_TELEGRAM_CHAT_ID",
)


def is_railway() -> bool:
    """True when running under a Railway (hosted single-container) deploy."""
    return os.environ.get("KOAN_DEPLOY", "").strip().lower() == "railway"


def required_env_present() -> bool:
    """True when env vars alone can provision a complete instance."""
    has_auth = any(os.environ.get(k, "").strip() for k in AUTH_KEYS)
    has_gh = bool(os.environ.get("GH_TOKEN", "").strip())
    has_tg = all(os.environ.get(k, "").strip() for k in TELEGRAM_KEYS)
    return has_auth and has_gh and has_tg


def env_configured() -> bool:
    """Env-var config counts as a valid instance only in hosted mode."""
    return is_railway() and required_env_present()


def write_env_from_environment(env_file: Path) -> None:
    """Materialize/refresh a .env from the process environment, preserving
    operator-added keys. Idempotent across re-deploys (a 'mirror' of the
    Railway service variables).

    The file holds secrets, so it is created/locked down to 0600. Raises
    RuntimeError if any key fails to write, so a botched mirror is not
    reported as complete."""
    env_file.parent.mkdir(parents=True, exist_ok=True)
    if not env_file.exists():
        env_file.write_text("# Generated by Kōan railway provisioning\n")
    # Secrets on disk: restrict to owner read/write only.
    with contextlib.suppress(OSError):
        os.chmod(env_file, 0o600)
    # Inline import to avoid an import cycle with onboarding_helpers.
    from app.onboarding_helpers import update_env_var
    failed = []
    for key in PROVISION_KEYS:
        val = os.environ.get(key, "").strip()
        if val and not update_env_var(key, val, env_file=env_file):
            failed.append(key)
    if failed:
        raise RuntimeError(
            f".env mirror incomplete — failed to write: {', '.join(failed)}"
        )


def daemon_running(koan_root) -> bool:
    """True when the run-loop daemon holds its pidfile."""
    try:
        from app.pid_manager import check_pidfile
        return bool(check_pidfile(Path(koan_root), "run"))
    except (OSError, ImportError) as exc:
        # Narrow: a genuine pidfile/IO error is visible, not silently
        # indistinguishable from "no daemon running".
        print(f"  daemon_running: pidfile check failed: {exc}")
        return False


def ensure_volume_writable(instance_dir: Path) -> tuple[bool, str]:
    """Best-effort make the instance volume writable by the running UID.

    Returns (ok, message). Tries os.chown when running as root; always
    verifies writability with a probe file. Surfaces a clear message on
    failure so callers (wizard) can report a permission error."""
    try:
        instance_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        return False, f"cannot create {instance_dir}: {exc}"
    # When the entrypoint runs as root but the daemon/terminal later runs as
    # an unprivileged UID (Railway can switch users between boot and exec),
    # KOAN_UID/KOAN_GID let us hand the volume to that target owner. Default
    # to the current UID/GID otherwise.
    if os.geteuid() == 0:
        target_uid = int(os.environ.get("KOAN_UID", os.getuid()))
        target_gid = int(os.environ.get("KOAN_GID", os.getgid()))
        try:
            for p in [instance_dir, *instance_dir.rglob("*")]:
                os.chown(p, target_uid, target_gid)
        except OSError:
            pass  # probe below is the source of truth
    probe = instance_dir / ".koan-write-probe"
    try:
        probe.write_text("ok")
        probe.unlink()
        return True, "writable"
    except OSError as exc:
        return False, (
            f"Permission denied writing to {instance_dir}: {exc}. "
            "On Railway, ensure the volume is mounted at /app/instance and "
            "KOAN_DEPLOY=railway so ownership is normalized at boot."
        )
