"""Tests for app.pr_footer — shared Kōan footer helpers."""

import os
import sys
from unittest.mock import patch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
os.environ.setdefault("KOAN_ROOT", "/tmp/test-koan")

from app.pr_footer import (
    append_koan_footer,
    build_mission_footer,
    build_koan_footer,
    build_pr_footer,
    format_duration,
    strip_legacy_footers,
    KOAN_URL,
)


class TestBuildKoanFooter:
    def test_default(self):
        result = build_koan_footer()
        assert result == f"_Generated by [Kōan]({KOAN_URL})_"

    def test_custom_action(self):
        result = build_koan_footer(action="Automated review by")
        assert result == f"_Automated review by [Kōan]({KOAN_URL})_"

    def test_provider_only(self):
        result = build_koan_footer(provider_name="claude")
        assert "Claude" in result
        assert f"[Kōan]({KOAN_URL})" in result
        assert "_(Claude)_" in result

    def test_model_only(self):
        result = build_koan_footer(model="opus-4-6")
        assert "model opus-4-6" in result
        assert f"[Kōan]({KOAN_URL})" in result

    def test_provider_and_model(self):
        result = build_koan_footer(provider_name="claude", model="opus-4-6")
        assert "_(Claude · model opus-4-6)_" in result
        assert f"[Kōan]({KOAN_URL})" in result

    def test_provider_capitalized(self):
        result = build_koan_footer(provider_name="copilot")
        assert "Copilot" in result

    def test_hyphenated_provider_label(self):
        result = build_koan_footer(provider_name="ollama-launch")
        assert "Ollama-launch" in result

    def test_review_footer_compat(self):
        result = build_koan_footer(
            action="Automated review by",
            provider_name="claude",
            model="opus-4-6",
        )
        expected = (
            f"_Automated review by [Kōan]({KOAN_URL})_"
            " _(Claude · model opus-4-6)_"
        )
        assert result == expected

    @patch("app.pr_footer._short_head", return_value="2b7761d")
    @patch("app.pr_footer.time.time", return_value=113.0)
    def test_pr_footer_with_runtime_metadata(self, _mock_time, _mock_head):
        result = build_pr_footer(
            provider_name="ollama-launch",
            model="qwen3.5:cloud",
            project_path="/repo",
            started_at=100,
        )
        assert f"[Kōan]({KOAN_URL})" in result
        assert "Ollama-launch" in result
        assert "model qwen3.5:cloud" in result
        assert "HEAD=2b7761d" in result
        assert "13s" in result

    def test_mission_footer_with_runtime_metadata(self):
        result = build_mission_footer(
            provider_name="claude",
            model="opus-4-6",
            head_sha="2b7761dabcdef",
            duration_seconds=300,
        )
        assert result == (
            f"_Generated by [Kōan]({KOAN_URL})_ "
            "_(Claude · model opus-4-6 · HEAD=2b7761d · 5 min)_"
        )

    def test_append_footer_is_idempotent(self):
        original = (
            "## Summary\n\nChanges.\n\n---\n"
            f"_Generated by [Kōan]({KOAN_URL})_ _(Claude · model old)_"
        )
        result = append_koan_footer(original, build_koan_footer(model="new"))
        assert result.count("Generated by") == 1
        assert "model old" not in result
        assert "model new" in result
        assert result.startswith("## Summary\n\nChanges.")


class TestFormatDuration:
    def test_seconds_only(self):
        assert format_duration(45) == "45s"

    def test_zero(self):
        assert format_duration(0) == "0s"

    def test_exact_minute(self):
        assert format_duration(60) == "1 min"

    def test_minutes_and_seconds(self):
        assert format_duration(334) == "5 min 34s"

    def test_many_minutes(self):
        assert format_duration(725) == "12 min 5s"

    def test_exact_hour(self):
        assert format_duration(3600) == "1 h"

    def test_hour_and_minutes(self):
        assert format_duration(4320) == "1 h 12 min"

    def test_float_input(self):
        assert format_duration(65.7) == "1 min 5s"


class TestStripLegacyFooters:
    def test_strip_star_footer(self):
        body = "## Summary\n\nChanges.\n\n*Generated by Kōan /fix*"
        result = strip_legacy_footers(body)
        assert "Generated by" not in result
        assert "Changes." in result

    def test_strip_italic_footer(self):
        body = "## Summary\n\nChanges.\n\n_Generated by Kōan `/claudemd`_"
        result = strip_legacy_footers(body)
        assert "Generated by" not in result

    def test_strip_claude_code_footer(self):
        body = "## Summary\n\nChanges.\n\n🤖 Generated with [Claude Code](https://claude.ai/code)"
        result = strip_legacy_footers(body)
        assert "Claude Code" not in result
        assert "Changes." in result

    def test_strip_claude_code_plain(self):
        body = "## Summary\n\nChanges.\n\n🤖 Generated with Claude Code"
        result = strip_legacy_footers(body)
        assert "Claude Code" not in result

    def test_strip_review_footer(self):
        body = "## Review\n\nFindings.\n\n_Automated review by Kōan_"
        result = strip_legacy_footers(body)
        assert "Automated review" not in result

    def test_strip_review_footer_with_link(self):
        body = f"## Review\n\n_Automated review by [Kōan]({KOAN_URL})_ _(Claude · model opus-4-6)_"
        result = strip_legacy_footers(body)
        assert "Automated review" not in result

    def test_strip_branded_footer(self):
        body = f"## Summary\n\nChanges.\n\n---\n_Generated by [Kōan]({KOAN_URL})_"
        result = strip_legacy_footers(body)
        assert "Generated by" not in result
        assert "---" not in result

    def test_strip_branded_footer_with_provider(self):
        body = (
            "## Summary\n\nChanges.\n\n---\n"
            f"_Generated by [Kōan]({KOAN_URL})_ _(Claude · model opus-4-6)_"
        )
        result = strip_legacy_footers(body)
        assert "Generated by" not in result

    def test_strip_multiple_footers(self):
        body = (
            "## Summary\n\nChanges.\n\n"
            "🤖 Generated with [Claude Code](https://claude.ai/code)\n\n"
            "---\n*Generated by Kōan post-mission quality pipeline*"
        )
        result = strip_legacy_footers(body)
        assert "Claude Code" not in result
        assert "Generated by" not in result
        assert "Changes." in result

    def test_strip_koan_without_accent(self):
        body = "## Summary\n\n*Generated by Koan /fix*"
        result = strip_legacy_footers(body)
        assert "Generated by" not in result

    def test_preserves_regular_content(self):
        body = "## Summary\n\nGenerated excellent results.\n\nNo footer here."
        result = strip_legacy_footers(body)
        assert result == body

    def test_collapses_trailing_separator(self):
        body = "## Summary\n\nChanges.\n\n---\n*Generated by Kōan*"
        result = strip_legacy_footers(body)
        assert result.endswith("Changes.")
        assert "---" not in result

    def test_empty_body(self):
        assert strip_legacy_footers("") == ""
