"""
Pre-fix diagnostic step for the /fix pipeline.

Runs a lightweight, read-only Claude invocation to analyze the issue and
produce a structured hypothesis before any code changes are attempted.
"""

import logging
import re
from pathlib import Path
from typing import Dict, Optional

from app.prompts import load_prompt_or_skill

logger = logging.getLogger(__name__)

_CONFIDENCE_RE = re.compile(r"CONFIDENCE:\s*(HIGH|MEDIUM|LOW)", re.IGNORECASE)
_SECTION_RE = re.compile(
    r"(?:^|\n)(HYPOTHESIS|CODE_PATHS|ANALYSIS):\s*\n?",
    re.IGNORECASE,
)

_READ_ONLY_TOOLS = [
    "Bash", "Glob", "Grep", "Read", "WebFetch", "WebSearch",
]


def run_diagnostic(
    project_path: str,
    issue_url: str,
    issue_title: str,
    issue_body: str,
    context: str = "",
    skill_dir: Optional[Path] = None,
) -> Dict[str, str]:
    """Run the diagnostic step and return parsed results.

    Returns a dict with keys: confidence, hypothesis, code_paths, analysis, raw.
    On any failure, returns a LOW-confidence result with the error in 'error'.
    """
    from app.cli_provider import run_command_streaming

    template_vars = dict(
        ISSUE_URL=issue_url,
        ISSUE_TITLE=issue_title,
        ISSUE_BODY=issue_body,
        CONTEXT=context or "No additional context.",
    )
    prompt = load_prompt_or_skill(skill_dir, "fix-diagnose", **template_vars)

    try:
        output = run_command_streaming(
            prompt,
            project_path,
            allowed_tools=sorted(_READ_ONLY_TOOLS),
            model_key="chat",
            max_turns=5,
            timeout=120,
        )
    except Exception as e:
        logger.warning("Diagnostic step failed: %s", e)
        return {
            "confidence": "LOW",
            "hypothesis": "",
            "code_paths": "",
            "analysis": "",
            "raw": "",
            "error": str(e),
        }

    return _parse_diagnostic(output or "")


def _parse_diagnostic(raw: str) -> Dict[str, str]:
    """Parse structured diagnostic output into a dict."""
    result = {
        "confidence": "LOW",
        "hypothesis": "",
        "code_paths": "",
        "analysis": "",
        "raw": raw,
    }

    if not raw.strip():
        return result

    conf_match = _CONFIDENCE_RE.search(raw)
    if conf_match:
        result["confidence"] = conf_match.group(1).upper()

    sections = _SECTION_RE.split(raw)
    current_key = None
    for part in sections:
        upper = part.strip().upper()
        if upper in ("HYPOTHESIS", "CODE_PATHS", "ANALYSIS"):
            current_key = upper.lower()
            continue
        if current_key and current_key in result:
            result[current_key] = part.strip()
            current_key = None

    return result


def format_diagnostic_context(diagnostic: Dict[str, str]) -> str:
    """Format a parsed diagnostic as context for the fix prompt."""
    if not diagnostic.get("hypothesis"):
        return ""

    parts = [
        "## Preliminary Diagnostic (treat as hypothesis, not ground truth)",
        "",
        f"**Confidence**: {diagnostic['confidence']}",
        f"**Hypothesis**: {diagnostic['hypothesis']}",
    ]
    if diagnostic.get("code_paths"):
        parts.extend(["", "**Relevant code paths**:", diagnostic["code_paths"]])
    if diagnostic.get("analysis"):
        parts.extend(["", "**Analysis**:", diagnostic["analysis"]])
    parts.extend([
        "",
        "> This diagnostic was generated by a lightweight pre-analysis. "
        "Verify the hypothesis against the actual code before relying on it. "
        "The root cause may differ from what is described above.",
    ])
    return "\n".join(parts)
